from pathlib import Path
import yaml

from analytics_platform.datasets.gold import build_risk_snapshot


class ReportEngine:

    BUILDERS = {
        "build_risk_snapshot": build_risk_snapshot,
    }

    def __init__(self, config_path):
        self.config_path = Path(config_path)
        self.config = self._load_config()

    def _load_config(self):
        with open(self.config_path, "r") as file:
            return yaml.safe_load(file)

    def run(self):
        report = self.config["report"]

        builder_name = report["dataset"]["builder"]

        if builder_name not in self.BUILDERS:
            raise ValueError(
                f"Unknown dataset builder: {builder_name}"
            )

        dataframe = self.BUILDERS[builder_name]()

        markdown = self._render_markdown(
            report,
            dataframe
        )

        output_path = Path(
            report["output"]["markdown"]
        )

        output_path.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        output_path.write_text(markdown)

        return output_path

    def _render_markdown(
        self,
        report,
        dataframe
    ):
        row = dataframe.iloc[0]

        volatility_pct = (
            row["volatility_30d"] * 100
        )

        drawdown_pct = (
            row["drawdown"] * 100
        )

        return f"""# {report["name"]}

{report["description"]}

## Market Snapshot

| Metric | Value |
|---|---:|
| SPY Close | {row["spy_close"]:.2f} |
| 200-Day Moving Average | {row["ma_200"]:.2f} |
| 30-Day Volatility | {volatility_pct:.2f}% |
| Drawdown | {drawdown_pct:.2f}% |
| 10Y-3M Yield Spread | {row["yield_spread_10y_3m"]:.2f}% |
| Unemployment Rate | {row["unemployment_rate"]:.2f}% |

## Data Dates

- Market data: {row["market_data_date"].date()}
- Yield data: {row["yield_data_date"].date()}
- Unemployment data: {row["unemployment_data_date"].date()}

---
Generated by Analytics Platform
"""
