import pandas as pd

from analytics_platform.reporting.charts import (
    render_line_chart,
)


def _format_value(value, fmt=None):
    if pd.isna(value):
        return "N/A"

    if fmt == "integer":
        return f"{value:,.0f}"

    if fmt == "decimal_2":
        return f"{value:,.2f}"

    if fmt == "percent_2":
        return f"{value * 100:.2f}%"

    return str(value)


def render_generic(report, dataframe):
    output = []

    output.append(f'# {report["name"]}')
    output.append("")

    description = report.get("description")

    if description:
        output.append(description)
        output.append("")

    sections = report.get(
        "sections",
        []
    )

    for section in sections:
        section_type = section["type"]

        if section_type == "coverage":
            output.extend(
                _render_coverage(
                    section,
                    dataframe
                )
            )

        elif section_type == "table":
            output.extend(
                _render_table(
                    section,
                    dataframe
                )
            )

        elif section_type == "latest":
            output.extend(
                _render_latest(
                    section,
                    dataframe
                )
            )

        elif section_type == "chart":
            output.extend(
                _render_chart(
                    section,
                    dataframe
                )
            )

        else:
            raise ValueError(
                f"Unknown section type: {section_type}"
            )

    output.append("")
    output.append("---")
    output.append("Generated by Analytics Platform")

    return "\n".join(output)


def _render_coverage(section, dataframe):
    title = section.get(
        "title",
        "Coverage"
    )

    year_column = section.get(
        "year_column",
        "year"
    )

    return [
        f"## {title}",
        "",
        f"- Earliest year: {int(dataframe[year_column].min())}",
        f"- Latest year: {int(dataframe[year_column].max())}",
        f"- Observations: {len(dataframe)}",
        (
            f"- Duplicate years: "
            f"{dataframe[year_column].duplicated().sum()}"
        ),
        "",
    ]


def _render_latest(section, dataframe):
    title = section.get(
        "title",
        "Latest Snapshot"
    )

    sort_by = section.get("sort_by")

    if sort_by:
        row = (
            dataframe
            .sort_values(sort_by)
            .iloc[-1]
        )
    else:
        row = dataframe.iloc[-1]

    lines = [
        f"## {title}",
        "",
        "| Metric | Value |",
        "|---|---:|",
    ]

    for field in section["fields"]:
        column = field["column"]
        label = field.get(
            "label",
            column
        )

        value = _format_value(
            row[column],
            field.get("format")
        )

        lines.append(
            f"| {label} | {value} |"
        )

    lines.append("")

    return lines


def _render_table(section, dataframe):
    title = section.get(
        "title",
        "Data"
    )

    filtered = dataframe.copy()

    year_column = section.get(
        "year_column"
    )

    years = section.get(
        "years"
    )

    if year_column and years:
        filtered = filtered[
            filtered[year_column].isin(years)
        ]

    columns = section["columns"]

    headers = [
        column.get(
            "label",
            column["column"]
        )
        for column in columns
    ]

    lines = [
        f"## {title}",
        "",
        "| " + " | ".join(headers) + " |",
        "|" + "|".join(
            ["---"] * len(headers)
        ) + "|",
    ]

    for _, row in filtered.iterrows():
        values = []

        for column in columns:
            value = _format_value(
                row[column["column"]],
                column.get("format")
            )

            values.append(value)

        lines.append(
            "| " + " | ".join(values) + " |"
        )

    lines.append("")

    return lines


def _render_chart(section, dataframe):
    title = section.get(
        "title",
        "Chart"
    )

    chart_type = section.get(
        "chart",
        "line"
    )

    if chart_type != "line":
        raise ValueError(
            f"Unsupported chart type: {chart_type}"
        )

    output_path = section["output"]

    chart_path = render_line_chart(
        dataframe=dataframe,
        x=section["x"],
        y=section["y"],
        title=title,
        output_path=output_path
    )

    markdown_path = section.get(
        "markdown_path",
        chart_path.as_posix()
    )

    return [
        f"## {title}",
        "",
        f"![{title}]({markdown_path})",
        "",
    ]
