from analytics_platform.reporting.generic_renderer import (
    render_generic,
)

def render_market_risk(report, dataframe):
    row = dataframe.iloc[0]

    volatility_pct = row["volatility_30d"] * 100
    drawdown_pct = row["drawdown"] * 100

    return f"""# {report["name"]}

{report.get("description", "")}

## Market Snapshot

| Metric | Value |
|---|---:|
| SPY Close | {row["spy_close"]:.2f} |
| 200-Day Moving Average | {row["ma_200"]:.2f} |
| 30-Day Volatility | {volatility_pct:.2f}% |
| Drawdown | {drawdown_pct:.2f}% |
| 10Y-3M Yield Spread | {row["yield_spread_10y_3m"]:.2f}% |
| Unemployment Rate | {row["unemployment_rate"]:.2f}% |

## Data Dates

- Market data: {row["market_data_date"].date()}
- Yield data: {row["yield_data_date"].date()}
- Unemployment data: {row["unemployment_data_date"].date()}

---
Generated by Analytics Platform
"""

def render_economic_history(report, dataframe):

    country = dataframe.iloc[0]["country"]

    useful = dataframe[
        dataframe[
            [
                "population",
                "gdp",
                "gdp_per_capita"
            ]
        ].notna().any(axis=1)
    ].copy()

    milestone_years = [
        -1000,
        1,
        1000,
        1500,
        1700,
        1800,
        1900,
        1950,
        1960,
        2000,
        2020,
        2025,
    ]

    selected = useful[
        useful["year"].isin(
            milestone_years
        )
    ]

    rows = []

    for _, row in selected.iterrows():

        population = (
            f'{row["population"]:,.0f}'
            if row["population"] == row["population"]
            else "N/A"
        )

        gdp = (
            f'{row["gdp"]:,.0f}'
            if row["gdp"] == row["gdp"]
            else "N/A"
        )

        gdppc = (
            f'{row["gdp_per_capita"]:,.2f}'
            if row["gdp_per_capita"]
            == row["gdp_per_capita"]
            else "N/A"
        )

        rows.append(
            f'| {int(row["year"])} '
            f'| {population} '
            f'| {gdp} '
            f'| {gdppc} |'
        )

    table_rows = "\n".join(rows)

    return f"""# {report["name"]}

{report.get("description", "")}

## {country}

| Year | Population | GDP | GDP per Capita |
|---:|---:|---:|---:|
{table_rows}

## Coverage

- Earliest year: {int(dataframe["year"].min())}
- Latest year: {int(dataframe["year"].max())}
- Canonical observations: {len(dataframe)}
- Duplicate years: {dataframe["year"].duplicated().sum()}

---
Generated by Analytics Platform
"""

RENDERERS = {
    "market_risk": render_market_risk,
    "economic_history": render_economic_history,
    "generic": render_generic,
}


def get_renderer(name):
    if name not in RENDERERS:
        raise ValueError(
            f"Unknown renderer: {name}"
        )

    return RENDERERS[name]
