from analytics_platform.reporting.generic_renderer import (
    render_generic,
)

from analytics_platform.reporting.charts import (
    build_market_risk_charts,
    build_economic_history_charts,
    build_forecasts_vs_facts_charts,
    build_decisions_vs_outcomes_charts,
)


# ============================================================
# MARKET RISK
# ============================================================

def render_market_risk(report, dataframe):
    row = dataframe.iloc[0]

    volatility_pct = (
        row["volatility_30d"] * 100
    )

    drawdown_pct = (
        row["drawdown"] * 100
    )

    charts = build_market_risk_charts()

    return f"""# {report["name"]}

{report.get("description", "")}

## Market Snapshot

| Metric | Value |
|---|---:|
| SPY Close | {row["spy_close"]:.2f} |
| 200-Day Moving Average | {row["ma_200"]:.2f} |
| 30-Day Volatility | {volatility_pct:.2f}% |
| Drawdown | {drawdown_pct:.2f}% |
| 10Y-3M Yield Spread | {row["yield_spread_10y_3m"]:.2f}% |
| Unemployment Rate | {row["unemployment_rate"]:.2f}% |

## Market Trend

![SPY vs 200-Day Moving Average]({charts["spy_ma200"]})

## Macro Risk Signals

![Yield Spread vs Unemployment]({charts["macro"]})

## Data Dates

- Market data: {row["market_data_date"].date()}
- Yield data: {row["yield_data_date"].date()}
- Unemployment data: {row["unemployment_data_date"].date()}

---
Generated by Analytics Platform
"""


# ============================================================
# ECONOMIC HISTORY
# ============================================================

def render_economic_history(report, dataframe):
    country = dataframe.iloc[0]["country"]

    useful = dataframe[
        dataframe[
            [
                "population",
                "gdp",
                "gdp_per_capita",
            ]
        ].notna().any(axis=1)
    ].copy()

    milestone_years = [
        -1000,
        1,
        1000,
        1500,
        1700,
        1800,
        1900,
        1950,
        1960,
        2000,
        2020,
        2025,
    ]

    selected = useful[
        useful["year"].isin(
            milestone_years
        )
    ]

    rows = []

    for _, row in selected.iterrows():
        population = (
            f'{row["population"]:,.0f}'
            if row["population"] == row["population"]
            else "N/A"
        )

        gdp = (
            f'{row["gdp"]:,.0f}'
            if row["gdp"] == row["gdp"]
            else "N/A"
        )

        gdppc = (
            f'{row["gdp_per_capita"]:,.2f}'
            if row["gdp_per_capita"]
            == row["gdp_per_capita"]
            else "N/A"
        )

        rows.append(
            f'| {int(row["year"])} '
            f'| {population} '
            f'| {gdp} '
            f'| {gdppc} |'
        )

    table_rows = "\n".join(rows)

    charts = build_economic_history_charts(
        dataframe,
        country,
    )

    population_chart = (
        f'![Population History]({charts["population"]})'
        if charts["population"]
        else "Not enough population data."
    )

    gdppc_chart = (
        f'![GDP per Capita History]({charts["gdp_per_capita"]})'
        if charts["gdp_per_capita"]
        else "Not enough GDP-per-capita data."
    )

    return f"""# {report["name"]}

{report.get("description", "")}

## {country}

## Population Through History

{population_chart}

## GDP per Capita Through History

{gdppc_chart}

## Historical Milestones

| Year | Population | GDP | GDP per Capita |
|---:|---:|---:|---:|
{table_rows}

## Coverage

- Earliest year: {int(dataframe["year"].min())}
- Latest year: {int(dataframe["year"].max())}
- Canonical observations: {len(dataframe)}
- Duplicate years: {dataframe["year"].duplicated().sum()}

---
Generated by Analytics Platform
"""


# ============================================================
# FORECASTS VS FACTS
# ============================================================

def render_forecasts_vs_facts(
    report,
    dataframe,
):
    df = dataframe.copy()

    if "forecast_type" not in df.columns:
        df["forecast_type"] = "forecast"

    df["forecast_type"] = (
        df["forecast_type"]
        .fillna("forecast")
    )

    # --------------------------------------------------------
    # Point forecasts
    # --------------------------------------------------------
    point = df[
        (df["forecast_operator"] == "eq")
        & df["percentage_error"].notna()
    ].copy()

    point["abs_percentage_error"] = (
        point["percentage_error"].abs()
    )

    closest = point.nsmallest(
        5,
        "abs_percentage_error",
    )

    biggest = point.nlargest(
        5,
        "abs_percentage_error",
    )

    # --------------------------------------------------------
    # Horizon buckets
    # --------------------------------------------------------
    def horizon_bucket(years):
        if years != years:
            return "Unknown"

        if years < 1:
            return "< 1 year"

        if years < 3:
            return "1–3 years"

        if years < 10:
            return "3–10 years"

        return "10+ years"

    point["horizon_bucket"] = (
        point["forecast_horizon_years"]
        .apply(horizon_bucket)
    )

    horizon_accuracy = (
        point
        .groupby("horizon_bucket")
        .agg(
            forecasts=(
                "forecast_id",
                "count",
            ),
            mean_abs_error=(
                "abs_percentage_error",
                "mean",
            ),
            median_abs_error=(
                "abs_percentage_error",
                "median",
            ),
        )
        .reset_index()
    )

    type_accuracy = (
        point
        .groupby("forecast_type")
        .agg(
            forecasts=(
                "forecast_id",
                "count",
            ),
            mean_abs_error=(
                "abs_percentage_error",
                "mean",
            ),
            median_abs_error=(
                "abs_percentage_error",
                "median",
            ),
        )
        .reset_index()
    )

    # --------------------------------------------------------
    # Helpers
    # --------------------------------------------------------
    def format_date(value):
        if value != value:
            return "N/A"

        try:
            return value.date()
        except AttributeError:
            return value

    def format_number(value):
        if value != value:
            return "N/A"

        return f"{value:.2f}"

    def ranking_table(data):
        rows = []

        for _, row in data.iterrows():
            rows.append(
                f'| {row["topic"]} '
                f'| {row["forecast_type"]} '
                f'| {format_date(row["forecast_date"])} '
                f'| {format_date(row["target_date"])} '
                f'| {row["forecast_horizon"]} '
                f'| {format_number(row["forecast_value"])} '
                f'| {format_number(row["actual_value"])} '
                f'| {row["abs_percentage_error"]:.2f}% |'
            )

        return "\n".join(rows)

    closest_rows = ranking_table(
        closest
    )

    biggest_rows = ranking_table(
        biggest
    )

    # --------------------------------------------------------
    # Horizon accuracy table
    # --------------------------------------------------------
    horizon_rows = []

    for _, row in horizon_accuracy.iterrows():
        horizon_rows.append(
            f'| {row["horizon_bucket"]} '
            f'| {int(row["forecasts"])} '
            f'| {row["mean_abs_error"]:.2f}% '
            f'| {row["median_abs_error"]:.2f}% |'
        )

    horizon_rows = "\n".join(
        horizon_rows
    )

    # --------------------------------------------------------
    # Forecast type accuracy table
    # --------------------------------------------------------
    type_rows = []

    for _, row in type_accuracy.iterrows():
        type_rows.append(
            f'| {row["forecast_type"]} '
            f'| {int(row["forecasts"])} '
            f'| {row["mean_abs_error"]:.2f}% '
            f'| {row["median_abs_error"]:.2f}% |'
        )

    type_rows = "\n".join(
        type_rows
    )

    # --------------------------------------------------------
    # Complete comparison table
    # --------------------------------------------------------
    comparison_rows = []

    for _, row in df.iterrows():
        error = (
            f'{row["percentage_error"]:.2f}%'
            if row["percentage_error"]
            == row["percentage_error"]
            else "N/A"
        )

        operator = row.get(
            "forecast_operator",
            "eq",
        )

        forecast_display = format_number(
            row.get("forecast_value")
        )

        if operator == "range":
            lower = row.get(
                "forecast_lower"
            )

            upper = row.get(
                "forecast_upper"
            )

            if (
                lower == lower
                and upper == upper
            ):
                forecast_display = (
                    f"{lower:.2f}–{upper:.2f}"
                )

        elif operator == "gt":
            forecast_display = (
                f"> {forecast_display}"
            )

        elif operator == "lt":
            forecast_display = (
                f"< {forecast_display}"
            )

        comparison_rows.append(
            f'| {row["category"]} '
            f'| {row["forecast_type"]} '
            f'| {row["topic"]} '
            f'| {format_date(row["forecast_date"])} '
            f'| {format_date(row["target_date"])} '
            f'| {row["forecast_horizon"]} '
            f'| {forecast_display} '
            f'| {format_number(row["actual_value"])} '
            f'| {error} '
            f'| {row["outcome_classification"]} |'
        )

    comparison_rows = "\n".join(
        comparison_rows
    )

    forecast_types = (
        df["forecast_type"]
        .value_counts()
        .to_dict()
    )

    type_summary = "\n".join(
        f"- {name}: {count}"
        for name, count
        in forecast_types.items()
    )

    # --------------------------------------------------------
    # Generate visuals
    # --------------------------------------------------------
    charts = (
        build_forecasts_vs_facts_charts(
            df
        )
    )

    scatter_chart = (
        f'![Forecast vs Actual]({charts["scatter"]})'
        if charts["scatter"]
        else "Not enough data."
    )

    error_chart = (
        f'![Largest Forecast Errors]({charts["errors"]})'
        if charts["errors"]
        else "Not enough data."
    )

    horizon_chart = (
        f'![Accuracy by Horizon]({charts["horizon"]})'
        if charts["horizon"]
        else "Not enough data."
    )

    return f"""# {report["name"]}

{report.get("description", "")}

## Summary

- Total comparisons: {len(df)}
- Quantitative point forecasts: {len(point)}
- Categories: {df["category"].nunique()}

### Forecast Types

{type_summary}

## Forecast vs Actual

{scatter_chart}

Points closer to the diagonal represent forecasts that were closer
to the observed outcome.

## Largest Forecast Errors

{error_chart}

## Accuracy by Forecast Horizon

{horizon_chart}

| Horizon | Forecasts | Mean Absolute Error | Median Absolute Error |
|---|---:|---:|---:|
{horizon_rows}

## Closest Forecasts

| Topic | Type | Forecast Made | Target | Horizon | Forecast | Actual | Absolute Error % |
|---|---|---|---|---|---:|---:|---:|
{closest_rows}

## Biggest Misses

| Topic | Type | Forecast Made | Target | Horizon | Forecast | Actual | Absolute Error % |
|---|---|---|---|---|---:|---:|---:|
{biggest_rows}

## Accuracy by Forecast Type

| Forecast Type | Forecasts | Mean Absolute Error | Median Absolute Error |
|---|---:|---:|---:|
{type_rows}

## All Forecasts vs Facts

| Category | Type | Topic | Forecast Made | Target | Horizon | Forecast | Actual | Error % | Classification |
|---|---|---|---|---|---|---:|---:|---:|---|
{comparison_rows}

---
Generated by Analytics Platform
"""


# ============================================================
# DECISIONS VS OUTCOMES
# ============================================================

def render_decisions_vs_outcomes(
    report,
    dataframe,
):
    df = dataframe.copy()

    rows = []

    for _, row in df.iterrows():
        decision_date = (
            row["decision_date"].date()
            if row["decision_date"]
            == row["decision_date"]
            else "N/A"
        )

        outcome_date = (
            row["outcome_date"].date()
            if row["outcome_date"]
            == row["outcome_date"]
            else "N/A"
        )

        horizon = (
            f'{row["outcome_horizon_years"]:.1f} years'
            if row.get(
                "outcome_horizon_years"
            )
            == row.get(
                "outcome_horizon_years"
            )
            else "N/A"
        )

        predicted = row.get(
            "claim_at_time",
            "N/A",
        )

        outcome = (
            f'{row["outcome_value"]:.2f} '
            f'{row.get("outcome_unit", "")}'
            if row["outcome_value"]
            == row["outcome_value"]
            else "N/A"
        )

        rows.append(
            f'| {row["category"]} '
            f'| {row["decision"]} '
            f'| {decision_date} '
            f'| {outcome_date} '
            f'| {horizon} '
            f'| {predicted} '
            f'| {outcome} '
            f'| {row["confidence"]} |'
        )

    table_rows = "\n".join(rows)

    charts = (
        build_decisions_vs_outcomes_charts(
            df
        )
    )

    comparison_chart = (
        f'![Prediction vs Outcome]({charts["comparison"]})'
        if charts["comparison"]
        else "Not enough comparable numeric data."
    )

    horizon_chart = (
        f'![Decision Horizons]({charts["horizon"]})'
        if charts["horizon"]
        else "Not enough horizon data."
    )

    return f"""# {report["name"]}

{report.get("description", "")}

## Summary

- Decisions analyzed: {len(df)}
- Categories: {df["category"].nunique()}
- Jurisdictions: {df["jurisdiction"].nunique()}

## Published Expectations vs Outcomes

{comparison_chart}

## Decision-to-Outcome Horizon

{horizon_chart}

## Decisions vs Outcomes

| Category | Decision | Decision Date | Outcome Date | Horizon | Claim at the Time | Observed Outcome | Confidence |
|---|---|---|---|---|---|---|---|
{table_rows}

## Interpretation Principle

Observed outcomes are reported separately from causal attribution.

A change occurring after a policy decision does not, by itself,
prove that the policy caused the entire observed effect.

---
Generated by Analytics Platform
"""


# ============================================================
# RENDERER REGISTRY
# ============================================================

RENDERERS = {
    "market_risk": render_market_risk,
    "economic_history": render_economic_history,
    "forecasts_vs_facts": render_forecasts_vs_facts,
    "decisions_vs_outcomes": render_decisions_vs_outcomes,
    "generic": render_generic,
}


def get_renderer(name):
    if name not in RENDERERS:
        raise ValueError(
            f"Unknown renderer: {name}"
        )

    return RENDERERS[name]
