from analytics_platform.reporting.generic_renderer import (
    render_generic,
)


def render_market_risk(report, dataframe):
    row = dataframe.iloc[0]

    volatility_pct = row["volatility_30d"] * 100
    drawdown_pct = row["drawdown"] * 100

    return f"""# {report["name"]}

{report.get("description", "")}

## Market Snapshot

| Metric | Value |
|---|---:|
| SPY Close | {row["spy_close"]:.2f} |
| 200-Day Moving Average | {row["ma_200"]:.2f} |
| 30-Day Volatility | {volatility_pct:.2f}% |
| Drawdown | {drawdown_pct:.2f}% |
| 10Y-3M Yield Spread | {row["yield_spread_10y_3m"]:.2f}% |
| Unemployment Rate | {row["unemployment_rate"]:.2f}% |

## Data Dates

- Market data: {row["market_data_date"].date()}
- Yield data: {row["yield_data_date"].date()}
- Unemployment data: {row["unemployment_data_date"].date()}

---
Generated by Analytics Platform
"""


def render_economic_history(report, dataframe):
    country = dataframe.iloc[0]["country"]

    useful = dataframe[
        dataframe[
            [
                "population",
                "gdp",
                "gdp_per_capita",
            ]
        ].notna().any(axis=1)
    ].copy()

    milestone_years = [
        -1000,
        1,
        1000,
        1500,
        1700,
        1800,
        1900,
        1950,
        1960,
        2000,
        2020,
        2025,
    ]

    selected = useful[
        useful["year"].isin(
            milestone_years
        )
    ]

    rows = []

    for _, row in selected.iterrows():
        population = (
            f'{row["population"]:,.0f}'
            if row["population"] == row["population"]
            else "N/A"
        )

        gdp = (
            f'{row["gdp"]:,.0f}'
            if row["gdp"] == row["gdp"]
            else "N/A"
        )

        gdppc = (
            f'{row["gdp_per_capita"]:,.2f}'
            if row["gdp_per_capita"]
            == row["gdp_per_capita"]
            else "N/A"
        )

        rows.append(
            f'| {int(row["year"])} '
            f'| {population} '
            f'| {gdp} '
            f'| {gdppc} |'
        )

    table_rows = "\n".join(rows)

    return f"""# {report["name"]}

{report.get("description", "")}

## {country}

| Year | Population | GDP | GDP per Capita |
|---:|---:|---:|---:|
{table_rows}

## Coverage

- Earliest year: {int(dataframe["year"].min())}
- Latest year: {int(dataframe["year"].max())}
- Canonical observations: {len(dataframe)}
- Duplicate years: {dataframe["year"].duplicated().sum()}

---
Generated by Analytics Platform
"""


def render_forecasts_vs_facts(report, dataframe):
    df = dataframe.copy()

    # ---------------------------------------------------------
    # Point forecasts only for percentage-error rankings
    # ---------------------------------------------------------
    point = df[
        (df["forecast_operator"] == "eq")
        & df["percentage_error"].notna()
    ].copy()

    point["abs_percentage_error"] = (
        point["percentage_error"].abs()
    )

    closest = point.nsmallest(
        5,
        "abs_percentage_error"
    )

    biggest = point.nlargest(
        5,
        "abs_percentage_error"
    )

    # ---------------------------------------------------------
    # Forecast horizon buckets
    # ---------------------------------------------------------
    def horizon_bucket(years):
        if years != years:
            return "Unknown"

        if years < 1:
            return "< 1 year"

        if years < 3:
            return "1–3 years"

        if years < 10:
            return "3–10 years"

        return "10+ years"

    point["horizon_bucket"] = (
        point["forecast_horizon_years"]
        .apply(horizon_bucket)
    )

    horizon_accuracy = (
        point
        .groupby(
            "horizon_bucket",
            dropna=False,
        )
        .agg(
            forecasts=(
                "forecast_id",
                "count",
            ),
            mean_abs_error=(
                "abs_percentage_error",
                "mean",
            ),
            median_abs_error=(
                "abs_percentage_error",
                "median",
            ),
        )
        .reset_index()
    )

    # ---------------------------------------------------------
    # Helpers
    # ---------------------------------------------------------
    def format_date(value):
        if value != value:
            return "N/A"

        try:
            return value.date()
        except AttributeError:
            return value

    def format_number(value):
        if value != value:
            return "N/A"

        return f"{value:.2f}"

    def ranking_table(data):
        rows = []

        for _, row in data.iterrows():
            rows.append(
                f'| {row["topic"]} '
                f'| {format_date(row["forecast_date"])} '
                f'| {format_date(row["target_date"])} '
                f'| {row["forecast_horizon"]} '
                f'| {format_number(row["forecast_value"])} '
                f'| {format_number(row["actual_value"])} '
                f'| {row["abs_percentage_error"]:.2f}% |'
            )

        if not rows:
            return (
                "| No data | N/A | N/A | N/A | "
                "N/A | N/A | N/A |"
            )

        return "\n".join(rows)

    # ---------------------------------------------------------
    # Closest / biggest misses
    # ---------------------------------------------------------
    closest_rows = ranking_table(
        closest
    )

    biggest_rows = ranking_table(
        biggest
    )

    # ---------------------------------------------------------
    # Horizon accuracy
    # ---------------------------------------------------------
    horizon_rows = []

    for _, row in horizon_accuracy.iterrows():
        horizon_rows.append(
            f'| {row["horizon_bucket"]} '
            f'| {int(row["forecasts"])} '
            f'| {row["mean_abs_error"]:.2f}% '
            f'| {row["median_abs_error"]:.2f}% |'
        )

    if horizon_rows:
        horizon_rows = "\n".join(
            horizon_rows
        )
    else:
        horizon_rows = (
            "| No data | 0 | N/A | N/A |"
        )

    # ---------------------------------------------------------
    # Complete comparison table
    # ---------------------------------------------------------
    comparison_rows = []

    for _, row in df.iterrows():
        error = (
            f'{row["percentage_error"]:.2f}%'
            if row["percentage_error"]
            == row["percentage_error"]
            else "N/A"
        )

        operator = row.get(
            "forecast_operator",
            "eq",
        )

        forecast_display = format_number(
            row.get("forecast_value")
        )

        if operator == "range":
            lower = row.get(
                "forecast_lower"
            )
            upper = row.get(
                "forecast_upper"
            )

            if (
                lower == lower
                and upper == upper
            ):
                forecast_display = (
                    f"{lower:.2f}–{upper:.2f}"
                )

        elif operator == "gt":
            forecast_display = (
                f"> {forecast_display}"
            )

        elif operator == "lt":
            forecast_display = (
                f"< {forecast_display}"
            )

        comparison_rows.append(
            f'| {row["category"]} '
            f'| {row["topic"]} '
            f'| {format_date(row["forecast_date"])} '
            f'| {format_date(row["target_date"])} '
            f'| {row["forecast_horizon"]} '
            f'| {forecast_display} '
            f'| {format_number(row["actual_value"])} '
            f'| {error} '
            f'| {row["outcome_classification"]} |'
        )

    comparison_rows = "\n".join(
        comparison_rows
    )

    # ---------------------------------------------------------
    # Summary statistics
    # ---------------------------------------------------------
    categories = (
        df["category"].nunique()
        if "category" in df.columns
        else 0
    )

    threshold_forecasts = (
        df["forecast_operator"]
        .isin(["gt", "lt"])
        .sum()
    )

    range_forecasts = (
        (
            df["forecast_operator"]
            == "range"
        )
        .sum()
    )

    return f"""# {report["name"]}

{report.get("description", "")}

## Summary

- Forecast comparisons: {len(df)}
- Point forecasts: {len(point)}
- Threshold forecasts: {threshold_forecasts}
- Range forecasts: {range_forecasts}
- Categories: {categories}

## Closest Forecasts

| Topic | Forecast Made | Target | Horizon | Forecast | Actual | Absolute Error % |
|---|---|---|---|---:|---:|---:|
{closest_rows}

## Biggest Misses

| Topic | Forecast Made | Target | Horizon | Forecast | Actual | Absolute Error % |
|---|---|---|---|---:|---:|---:|
{biggest_rows}

## Accuracy by Forecast Horizon

| Horizon | Forecasts | Mean Absolute Error | Median Absolute Error |
|---|---:|---:|---:|
{horizon_rows}

## All Forecasts vs Facts

| Category | Topic | Forecast Made | Target | Horizon | Forecast | Actual | Error % | Classification |
|---|---|---|---|---|---:|---:|---:|---|
{comparison_rows}

---
Generated by Analytics Platform
"""


RENDERERS = {
    "market_risk": render_market_risk,
    "economic_history": render_economic_history,
    "forecasts_vs_facts": render_forecasts_vs_facts,
    "generic": render_generic,
}


def get_renderer(name):
    if name not in RENDERERS:
        raise ValueError(
            f"Unknown renderer: {name}"
        )

    return RENDERERS[name]
